version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
        name: docker build complete image
        command: docker build --file Dockerfile --tag demo:build .
     - run:
        name: docker build and test --target test
        command: docker build --file Dockerfile --target test --tag demo:test . && docker run demo:test
