version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run:
        name: Build
        command: ls -lah && docker build --file Dockerfile --tag demo:build .
     - run:
        name: Test
        command: ls -lah && docker build --file Dockerfile --target test --tag demo:test . && docker run demo:test .